# Generated by Django 4.2.1 on 2023-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
