# Generated by Django 4.2.1 on 2023-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0002_transaction_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=11, null=True),
        ),
    ]
